language: objective-c
osx_image: xcode9.1
rvm:
- 2.4.2
install:
- gem install xcpretty
script:
- xcodebuild -project Resolver.xcodeproj -scheme "Resolver-iOS" | xcpretty
- xcodebuild -project Resolver.xcodeproj -scheme "Resolver-macOS" | xcpretty
after_success:
- "./docs/build_docs.sh"
before_deploy:
- carthage build --no-skip-current
- carthage archive Resolver
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: KCYuFcrjWYRv0Mu6oOcF6VVsiMIWyQrKiCRT3FF+lHv8zLd/iz7NIAallUyWtsrK3tHX0jfVJeCau5IHI6sk9/8+PtSmg62PzCZw+8fHnGKXM135VVQa+dSAKU+/ZIyApZuqkSM8bsisrDzIHYylHgP4nI1t9iOdy4WCaXTEEYdBXpJTb6igqaqI2Sr4bsF+IOy5H+U8Xxn6YjU9Ml19M2zgOLQQjxdnW8JLlLG6RCu8Oo9E32KCwsktupzDioC8rhvNpxPSA29Qrj5E2ITxxk4ZZCgWc8Ggaqsuo3d9TEXqhbJRH9aK/uxPaoRldWF0cTn4tWpSmyyOQ0GVb7okgswCm8KFibEOKk0kwoPekngBAlSPAhRQOc03PgrRM+VzCuesX1/Y2tix1Kul4dAFy6pHWrs+/jZXMLih/SugedZINwnn9y8s/DyDGlrAgFAagIoaurUn0SRQkzm6HvWi0I2Tjie3CCHx1sBm3E3eEzSIF1IlYZH29gKnaKeuF3AoP1toiawsUIjXqK/TRT3Wbup+zlrGgysjUwVpDqF7HpEhXkvh6Dz3RF4Z4KQomdHjvdGTbekoCdJDpuOnrLIgt2z0ChhuVJP54I681TQg2LlWbocCvSP/kJN6QFDp+tlw33ueRdnAqx89Z/Rj3c1ifgCEFxAoaHWQYMBwd0UbGkk=
  file: Resolver.framework.zip
  on:
    repo: Hmyy/Resolver
    tag: true
